# -*- coding: utf-8 -*-
"""Copy of Redera_Linear.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S6qFaziOOQbPsMrvg64hu3o4hF6GiG8p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

data = pd.read_csv('Lesson_4_student_grades_dataset.csv',encoding = "latin -1")
data.head()

plt.scatter(data['Travel_Time_to_School'],data['Attendance_Percentage'])
plt.xlabel('Independent Variavle')
plt.ylabel('Dependent Variable')
plt.title('Linear Regression')
plt.show()

X = data[['Travel_Time_to_School']]
Y = data[['Attendance_Percentage']]

model = LinearRegression()
model.fit(X,Y)

slope = model.coef_[0]
intercept = model.intercept_
print('Slope',slope)
print('Intercept',intercept)

plt.scatter(X,Y)
plt.plot(X, model.predict (X),color='red')
plt.xlabel('Independent Variable')
plt.ylabel('Dependent Variabel')
plt.title('Linear Regression')
plt.show

new_X =[[np.random.randint(100,200)]]
predicted_Y = model.predict(new_X)
print('Value of X:',new_X)
print('Predicted Value of Y:',predicted_Y)